create table public.activation_tokens
(
    created_at timestamp(6),
    expires_at timestamp(6) not null,
    id         bigint generated by default as identity
        primary key,
    member_id  bigint       not null
        unique,
    token      varchar(255) not null
);

alter table public.activation_tokens
    owner to testuser;

create table public.comments
(
    author_member_id  bigint       not null,
    created_at        timestamp(6) not null,
    id                bigint generated by default as identity
        primary key,
    parent_comment_id bigint,
    post_id           bigint       not null,
    reply_count       bigint       not null,
    updated_at        timestamp(6) not null,
    author_nickname   varchar(20)  not null,
    content_text      text         not null,
    status            varchar(255) not null constraint comments_status_check
            check ((status)::text = ANY ((ARRAY ['PUBLISHED'::character varying, 'DELETED'::character varying])::text[]))
);

alter table public.comments
    owner to testuser;

create index idx_comment_post_id
    on public.comments (post_id);

create index idx_comment_author_id
    on public.comments (author_member_id);

create index idx_comment_parent_id
    on public.comments (parent_comment_id);

create index idx_comment_status
    on public.comments (status);

create index idx_comment_created_at
    on public.comments (created_at);

create table public.follows
(
    created_at                 timestamp(6) not null,
    follower_id                bigint       not null,
    follower_profile_image_id  bigint       not null,
    following_id               bigint       not null,
    following_profile_image_id bigint       not null,
    id                         bigint generated by default as identity
        primary key,
    updated_at                 timestamp(6),
    follower_nickname          varchar(50)  not null,
    following_nickname         varchar(50)  not null,
    status                     varchar(255) not null constraint follows_status_check
            check ((status)::text = ANY
                   ((ARRAY ['ACTIVE'::character varying, 'UNFOLLOWED'::character varying, 'BLOCKED'::character varying])::text[])),
    unique (follower_id, following_id)
);

alter table public.follows
    owner to testuser;

create index idx_follow_follower_id
    on public.follows (follower_id);

create index idx_follow_following_id
    on public.follows (following_id);

create index idx_follow_status
    on public.follows (status);

create index idx_follow_created_at
    on public.follows (created_at);

create table public.friendships
(
    created_at       timestamp(6) not null,
    friend_image_id  bigint       not null,
    friend_member_id bigint       not null,
    id               bigint generated by default as identity
        primary key,
    image_id         bigint       not null,
    member_id        bigint       not null,
    updated_at       timestamp(6) not null,
    status           varchar(20)  not null constraint friendships_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'ACCEPTED'::character varying, 'REJECTED'::character varying, 'UNFRIENDED'::character varying])::text[])),
    friend_nickname  varchar(50),
    member_nickname  varchar(50),
    unique (member_id, friend_member_id)
);

alter table public.friendships
    owner to testuser;

create index idx_friendship_member_id
    on public.friendships (member_id);

create index idx_friendship_friend_member_id
    on public.friendships (friend_member_id);

create index idx_friendship_friend_nickname
    on public.friendships (friend_nickname);

create index idx_friendship_status
    on public.friendships (status);

create index idx_friendship_created_at
    on public.friendships (created_at);

create table public.images
(
    is_deleted  boolean      not null,
    id          bigint generated by default as identity
        primary key,
    uploaded_by bigint       not null,
    file_key    varchar(255) not null
        unique,
    image_type  varchar(255) not null constraint images_image_type_check
            check ((image_type)::text = ANY
                   ((ARRAY ['POST_IMAGE'::character varying, 'PROFILE_IMAGE'::character varying, 'THUMBNAIL'::character varying])::text[]))
);

alter table public.images
    owner to testuser;

create index idx_uploaded_by
    on public.images (uploaded_by);

create index idx_image_type
    on public.images (image_type);

create table public.member_event
(
    is_read            boolean      not null,
    created_at         timestamp(6) not null,
    id                 bigint generated by default as identity
        primary key,
    member_id          bigint       not null,
    related_comment_id bigint,
    related_member_id  bigint,
    related_post_id    bigint,
    event_type         varchar(30)  not null constraint member_event_event_type_check
            check ((event_type)::text = ANY
                   ((ARRAY ['FRIEND_REQUEST_SENT'::character varying, 'FRIEND_REQUEST_RECEIVED'::character varying, 'FRIEND_REQUEST_ACCEPTED'::character varying, 'FRIEND_REQUEST_REJECTED'::character varying, 'FRIENDSHIP_TERMINATED'::character varying, 'POST_CREATED'::character varying, 'POST_DELETED'::character varying, 'POST_COMMENTED'::character varying, 'COMMENT_CREATED'::character varying, 'COMMENT_DELETED'::character varying, 'COMMENT_REPLIED'::character varying, 'PROFILE_UPDATED'::character varying, 'ACCOUNT_ACTIVATED'::character varying, 'ACCOUNT_DEACTIVATED'::character varying])::text[])),
    title              varchar(100) not null,
    message            varchar(500) not null
);

alter table public.member_event
    owner to testuser;

create index idx_member_event_member_id
    on public.member_event (member_id);

create index idx_member_event_event_type
    on public.member_event (event_type);

create index idx_member_event_is_read
    on public.member_event (is_read);

create index idx_member_event_created_at
    on public.member_event (created_at);

create table public.member_detail
(
    activated_at    timestamp(6),
    deactivated_at  timestamp(6),
    id              bigint generated by default as identity
        primary key,
    image_id        bigint,
    registered_at   timestamp(6),
    profile_address varchar(15)
        unique,
    introduction    varchar(500),
    address         varchar(255)
);

alter table public.member_detail
    owner to testuser;

create table public.password_reset_tokens
(
    created_at timestamp(6) not null,
    expires_at timestamp(6) not null,
    id         bigint generated by default as identity
        primary key,
    member_id  bigint       not null,
    token      varchar(255) not null
        unique
);

alter table public.password_reset_tokens
    owner to testuser;

create index idx_password_reset_token
    on public.password_reset_tokens (token);

create index idx_password_reset_member_id
    on public.password_reset_tokens (member_id);

create table public.post_collections
(
    created_at      timestamp(6) not null,
    id              bigint generated by default as identity
        primary key,
    owner_member_id bigint       not null,
    updated_at      timestamp(6) not null,
    name            varchar(100) not null,
    cover_image_url varchar(500),
    description     text,
    owner_nickname  varchar(255) not null,
    privacy         varchar(255) not null constraint post_collections_privacy_check
            check ((privacy)::text = ANY ((ARRAY ['PUBLIC'::character varying, 'PRIVATE'::character varying])::text[])),
    status          varchar(255) not null constraint post_collections_status_check
            check ((status)::text = ANY ((ARRAY ['ACTIVE'::character varying, 'DELETED'::character varying])::text[]))
);

alter table public.post_collections
    owner to testuser;

create table public.collection_posts
(
    display_order integer not null,
    collection_id bigint  not null constraint fkr71d636l9ctei4h0nnkkkag3e
            references public.post_collections,
    post_id       bigint  not null,
    primary key (display_order, collection_id)
);

alter table public.collection_posts
    owner to testuser;

create index idx_collection_owner_member_id
    on public.post_collections (owner_member_id);

create index idx_collection_privacy_status
    on public.post_collections (privacy, status);

create index idx_collection_created_at
    on public.post_collections (created_at);

create index idx_collection_status
    on public.post_collections (status);

create table public.post_hearts
(
    created_at timestamp(6) not null,
    id         bigint generated by default as identity
        primary key,
    member_id  bigint       not null,
    post_id    bigint       not null,
    constraint uk_post_heart_post_member
        unique (post_id, member_id)
);

alter table public.post_hearts
    owner to testuser;

create index idx_post_heart_post_id
    on public.post_hearts (post_id);

create index idx_post_heart_member_id
    on public.post_hearts (member_id);

create table public.posts
(
    comment_count        integer          not null,
    heart_count          integer          not null,
    rating               integer          not null,
    restaurant_latitude  double precision not null,
    restaurant_longitude double precision not null,
    view_count           integer          not null,
    author_image_id      bigint           not null,
    author_member_id     bigint           not null,
    created_at           timestamp(6)     not null,
    id                   bigint generated by default as identity
        primary key,
    updated_at           timestamp(6)     not null,
    author_nickname      varchar(20)      not null,
    restaurant_name      varchar(100)     not null,
    author_introduction  varchar(500)     not null,
    content_text         text             not null,
    restaurant_address   varchar(255)     not null,
    status               varchar(255)     not null constraint posts_status_check
            check ((status)::text = ANY ((ARRAY ['PUBLISHED'::character varying, 'DELETED'::character varying])::text[]))
);

alter table public.posts
    owner to testuser;

create table public.post_images
(
    image_order integer not null,
    image_id    bigint  not null,
    post_id     bigint  not null constraint fko1i5va2d8de9mwq727vxh0s05
            references public.posts,
    primary key (image_order, post_id)
);

alter table public.post_images
    owner to testuser;

create index idx_post_author_id
    on public.posts (author_member_id);

create index idx_post_status
    on public.posts (status);

create index idx_post_created_at
    on public.posts (created_at);

create index idx_post_restaurant_name
    on public.posts (restaurant_name);

create table public.trust_score
(
    ad_review_count         integer,
    real_money_review_count integer,
    trust_score             integer,
    id                      bigint generated by default as identity
        primary key,
    trust_level             varchar(255) constraint trust_score_trust_level_check
            check ((trust_level)::text = ANY
                   ((ARRAY ['BRONZE'::character varying, 'SILVER'::character varying, 'GOLD'::character varying, 'DIAMOND'::character varying])::text[]))
);

alter table public.trust_score
    owner to testuser;

create table public.members
(
    detail_id       bigint       not null
        unique constraint fkawl3m8yvo16wgowaam7fi3x1p
            references public.member_detail,
    follower_count  bigint       not null,
    following_count bigint       not null,
    id              bigint generated by default as identity
        primary key,
    post_count      bigint       not null,
    trust_score_id  bigint
        unique constraint fkh5w2qukccwyysqrxaxe0hy93t
            references public.trust_score,
    updated_at      timestamp(6),
    nickname        varchar(20)  not null,
    email           varchar(255) not null
        unique,
    password_hash   varchar(255) not null,
    status          varchar(255) not null constraint members_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'ACTIVE'::character varying, 'DEACTIVATED'::character varying])::text[]))
);

alter table public.members
    owner to testuser;

create table public.member_roles
(
    member_id bigint not null constraint fk431yrnsn5s4omvwjvl9dre1n0
            references public.members,
    role      varchar(255) constraint member_roles_role_check
            check ((role)::text = ANY
                   ((ARRAY ['USER'::character varying, 'ADMIN'::character varying, 'MANAGER'::character varying])::text[]))
);

alter table public.member_roles
    owner to testuser;

create index idx_member_email
    on public.members (email);

create index idx_member_nickname
    on public.members (nickname);

create index idx_member_status
    on public.members (status);
